### ISSUE TITLE
Build branch

### ISSUE THREAD

**Issue by a1rwulf** [garbear/OpenELEC.tv#3]
Seems you have used the retroplayer-gl branch for the OE build with mupen64.
You've bumped the game addons and use the fixed buttonmap.
Therefore you will also need https://github.com/a1rwulf/OpenELEC.tv/commit/da931426da21fc89db4e7564f31d9f552bfaa450 so that c-buttons work correctly.

**Comment by garbear** [comment]
cherry picked. you can PR any other fixes I'm missing

**Comment by a1rwulf** [comment]
ok - nothing found so far.

**Comment by garbear** [comment]
game.libretro.mupen64plus also needs these patches, right?

**Comment by a1rwulf** [comment]
not sure what you mean?
The corresponding buttonmap is already in:
https://github.com/kodi-game/game.libretro.mupen64plus/commit/0d535abae31f8790d972e9be9d2b3f75209e8b06

**Comment by garbear** [comment]
the patches to emulate_game_controller_via_libretro.c haven't been placed here: https://github.com/kodi-game/game.libretro.mupen64plus/tree/master/depends/common/mupen64plus so with the add-on build system won't patch mupen64plus

**Comment by a1rwulf** [comment]
ah ok - didn't know that we could place patches in here.
So I can just place the patch in here without further actions needed?

**Comment by garbear** [comment]
https://github.com/kineticgar/game.netplay/tree/master/depends/common/protobuf
