### ISSUE TITLE
32 bit build not working

### ISSUE THREAD

**Issue by Pennykoin** [garbear/OpenELEC.tv#6]

**Comment by garbear** [comment]
Try LibreELEC

**Comment by Pennykoin** [comment]
32 bit system, i don't think I know enough to create my own 32 bit version,
was hoping this would build for that reason.

**Comment by garbear** [comment]
This repo hasn't been touched in over 3 years. what makes you think it will build?

**Comment by Pennykoin** [comment]
Hope I guess, lol.  Was hoping that it was just dusty & not broke I
guess, thanks for your time, feel free to kill the issue.
